version: '3'
services:
  redis:
    image: redis
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  front:
    image: front-end
    ports:
      - 5000:80
    links:
      - redis
  worker:
    image: worker
    links: 
      - redis
      - db
  results:
    image: show-results
    ports:
      - 5001:80
    links:
      - db
